my_app/urls.py
from django.urls import path
from . import views
app_name='my_app'

urlpatterns=[
    path('',views.my_app_index,name='home'),
    path('gallary',views.my_app_gallary,name='gallary'),
    path('players',views.my_app_players,name='players'),
    path('about',views.my_app_about,name='about'),
    path('contact',views.my_app_contact,name='contact'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path ,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_app.urls')),
]

my_app/models.py
from django.db import models

# Create your models here.

my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def my_app_index(request):
    return render(request,'my_app_templates/index.html')

def my_app_gallary(request):
    return render(request,'my_app_templates/gallary.html')

def my_app_players(request):
    return render(request,'my_app_templates/players.html')

def my_app_about(request):
    return render(request,'my_app_templates/about.html')

def my_app_contact(request):
    return render(request,'my_app_templates/contact.html')

my_app/templates/my_app_templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_about.css' %}">
    <title>About page</title>
</head>

<body>
    <div class="container1">

        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>
        <div class="navRight">

            <a href="{% url 'my_app:home' %}">Home</a>
            <a href="{% url 'my_app:gallary' %}">Gallary</a>
            <a href="{% url 'my_app:players' %}">Players</a>
            <a href="{% url 'my_app:about' %}">About Us</a>
            <a href="{% url 'my_app:contact' %}">Contact Us</a>

        </div>
    </div>
    <br><br><br><br>

    <div class="mainImage">
        <div><img src="{% static 'images/aboutimage.jpg' %}" alt=""></div>
    </div>

    <div class="container2">
        <div class="hist">
            <h1>History</h1>
        </div>
        <div class="para">
            <p>At the outset, there is nothing significant about the year 1721, as far as India's political history is
                concerned.
                Aurangzeb, the sixth of the great Mughals, had passed away in 1707, and the Empire he and his
                forefathers had built, had
                started to disintegrate. The Marathas were gaining in prominence, and in the process of knocking hard on
                the doors of
                Delhi. These were prominent happenings; what was peripheral was that 'merchants' from England and France
                had established
                'settlements' in select areas of the subcontinent, and were going about their business of trade.
                <br><br><br><br>
                The sea-route being the sole link between them and their respective homelands, most of these settlements
                were situated
                in the coastal areas of the Indian peninsula.
                <br><br><br><br>


                It was sometime in 1721 that a British ship dropped anchor off the coast of Kutch in western India. The
                recreational
                activities the sailors indulged in on the coast elicited curious reactions from onlookers. One of the
                sailors, who
                answered to the name of Downing, recalled his time on the Kutch coast in his memoirs thus: "We everyday
                diverted
                ourselves with playing cricket and other exercises"
                <br><br><br><br>
                This is the earliest recorded reference to cricket in India.

                As the merchants metamorphosed into rulers, they continued to demonstrate their recreational pursuits on
                Indian soil.
                The British army took on the English settlers in what was the first recorded cricket match in India in
                1751.
                <br><br><br><br>
                The establishment of the Calcutta Cricket Club (what we know today as CC & FC) in 1792, was another
                watershed for the
                sport in the land. In fact, it is the second-oldest cricket club in the world, after the MCC (1787).

                Ten years after its inception, the CCC organized a match between its team and the Old Etonians. The
                highlight of the
                game was Old Etonian Robert Vansittart's hundred. It was the first 'recorded' century on Indian soil.
                <br><br><br><br>
                That game was watched by the locals, as were other encounters that took place elsewhere.

                It was but natural that the locals sought to copy what the 'rulers' were doing. Recent evidence suggests
                that members of
                the Indian army were among the first to take to the sport. The 'sepoys' of regiments based in Sylhet
                (now part of
                Bangladesh) were reported by a periodical of the time as being more energetic and cheerful cricketers
                than their
                European superiors. The latter did not mind this, and were in fact happy to engage in matches against
                their
                subordinates.
                <br><br><br><br>
                The Parsis were the first Indian civilian community to take to cricket. They set up the Oriental Cricket
                Club in Mumbai
                in 1848. It did a premature death, but the community then established the Young Zoroastrians Club in
                1850. They were
                followed by the Hindus, who formed the Hindu Gymkhana in 1866. The scene of the cricketing activities of
                the Mumbai
                locals was the Esplanade 'maidan,' which was situated in front of the western ramparts of the erstwhile
                Bombay 'Fort'
                (demolished in 1860). At the far end of this 'maidan' was a plot of land that was out of bounds for dogs
                and Indians -
                the Bombay Gymkhana.
                <br><br><br><br>
                Cricket was also gaining in popularity in other cities at around the same time. 1884 was an eventful
                year, in that a
                team from Sri Lanka played a match in Kolkata. It was the country's first shot at international cricket.
                The Parsi
                Gymkhana was set up in Mumbai in the same year. A year later, Kolkata hosted a match between the
                Presidency Club and a
                team from Australia.
                <br><br><br><br>
                The relative economic stability of the Parsis was instrumental in their sending a team on a tour of
                England in 1886. Dr.
                D.H. Patel, one of the leading cricketers of the time, was named captain.
                <br><br><br><br>
                At the team's send-off in Bombay, Pherozeshah Mehta, one of the eminent Indians of the time, stated the
                squad's
                objective; "As artists go to Italy to do homage to the Great Masters, or as pilgrims go to Jerusalem to
                worship at a
                shrine, so now the Parsis are going to England to pay homage to the English cricketers, to learn
                something of that noble
                and manly pastime in the very country that is cricket's chosen home."
            </p>
        </div>



        <br><br><br><br><br>



    </div>

    <!-- FOOTER -->
    <div class="footer">
        <div>
            <h1>T +91 22 - 2289 8800

                F 022 - 2289 8801</h1>
        </div>
        <div>
            <h1>Copyrights BCCI 2021 , All Rights Reserved.</h1>
        </div>
        <div>
            <h1>Terms and Conditions</h1>
        </div>
        <div>
            <h1>Privacy Policy</h1>
        </div>

    </div>
</body>

my_app/templates/my_app_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <title>{% block title %}base{% endblock %}</title>
</head>

<body>
    <div class="container1">

        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>
        <div class="navRight">

            <a href="{% url 'my_app:home' %}">Home</a>
            <a href="{% url 'my_app:gallary' %}">Gallary</a>
            <a href="{% url 'my_app:players' %}">Players</a>
            <a href="{% url 'my_app:about' %}">About Us</a>
            <a href="{% url 'my_app:contact' %}">Contact Us</a>

        </div>
    </div>


    {% block content %}{% endblock %}
    

    <!-- footer -->

    <br><br><br><br>
    <div class="footer">
        <div>
            <h1>T +91 22 - 2289 8800

                F 022 - 2289 8801</h1>
        </div>
        <div>
            <h1>Copyrights BCCI 2021 , All Rights Reserved.</h1>
        </div>
        <div>
            <h1>Terms and Conditions</h1>
        </div>
        <div>
            <h1>Privacy Policy</h1>
        </div>

    </div>




</body>

my_app/templates/my_app_templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_contact.css' %}">
    <title>Contact page</title>
</head>

<body>
    <div class="container1">

        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>
        <div class="navRight">

            <a href="{% url 'my_app:home' %}">Home</a>
            <a href="{% url 'my_app:gallary' %}">Gallary</a>
            <a href="{% url 'my_app:players' %}">Players</a>
            <a href="{% url 'my_app:about' %}">About Us</a>
            <a href="{% url 'my_app:contact' %}">Contact Us</a>

        </div>
    </div>

    <div class="contactUs">

        <div class="title">
            <h2>Get in Touch</h2>
        </div>
        <div class="box">
            <!-- form -->
            <div class="contact form">
                <h3>Send a Message</h3>
                <form>
                    <div class="formBox">
                        <div class="row50">
                            <div class="inputBox">
                                <span>First Name</span>
                                <input type="text" placeholder="First Name">
                            </div>
                            <div class="inputBox">
                                <span>Last Name</span>
                                <input type="text" placeholder="Last Name">
                            </div>
                        </div>

                        <div class="row50">
                            <div class="inputBox">
                                <span>Email</span>
                                <input type="text" placeholder="Email">
                            </div>
                            <div class="inputBox">
                                <span>Mobile</span>
                                <input type="text" placeholder="Mobile No">
                            </div>
                        </div>
                        <div class="row100">
                            <div class="inputBox">
                                <span>Message</span>
                                <textarea placeholder="Write your message here.."></textarea>
                            </div>
                        </div>

                        <div class="row100">
                            <div class="inputBox">

                                <input type="submit" value="send">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- info box -->
            <div class="contact info">
                <h3>Contact info</h3>
                <div class="infoBox">
                    <div>
                        <span></span>
                        <p>BOARD OF CONTROL FOR CRICKET IN INDIA <br>
                            4th Floor, Cricket Centre <br>
                            Wankhede Stadium <br>
                            ‘D’ Road, Churchgate <br>
                            Mumbai- 400020 <br>
                            India</p>
                    </div>
                    <div>
                        <span></span>
                        <a href="mailto:bcci@email.com">bcci@email.com</a>
                    </div>

                    <div>
                        <span></span>
                        <a href="tel:  022 - 2289 8800">T 022 - 2289 8800</a>
                        <br>
                        <a href="tel:  022 - 2289 8800">T 022 - 2289 8800</a>
                    </div>

                </div>

            </div>
            <!-- map -->
            <div class="contact map">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d45935.861676268!2d80.11078851133882!3d12.968244850314333!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a525ff8c180b5a7%3A0x2a00cac08396946d!2sBCCI!5e0!3m2!1sen!2sin!4v1670604444811!5m2!1sen!2sin"
                    style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
                </iframe>
            </div>
        </div>

    </div>
    <!--  social media logo -->

    <div class="appLogo">
        <a href=""><img src="{% static 'images/socialmedia.png' %}" alt=""></a>
    </div>

    <br><br><br><br>

    <div class="container4">
        <div><img src="{% static 'images/byjus.png' %}" alt=""></div>
        <div><img src="{% static 'images/star.png' %}" alt=""></div>
        <div><img src="{% static 'images/mpl.png' %}" alt=""></div>
        <div><img src="{% static 'images/hyundai.png' %}" alt=""></div>
        <div><img src="{% static 'images/dream11.png' %}" alt=""></div>
        <div><img src="{% static 'images/ambuja.png' %}" alt=""></div>
        <div><img src="{% static 'images/master-card.png' %}" alt=""></div>


    </div>
    <br><br><br>




    <!-- FOOTER -->
    <div class="footer">
        <div>
            <h1>T +91 22 - 2289 8800

                F 022 - 2289 8801</h1>
        </div>
        <div>
            <h1>Copyrights BCCI 2021 , All Rights Reserved.</h1>
        </div>
        <div>
            <h1>Terms and Conditions</h1>
        </div>
        <div>
            <h1>Privacy Policy</h1>
        </div>

    </div>

</body>

my_app/templates/my_app_templates/gallary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_gallary.css' %}">
    <title>Gallary page</title>
</head>

<body>
    <div class="container1">

        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>
        <div class="navRight">
            <a href="{% url 'my_app:home' %}">Home</a>
            <a href="{% url 'my_app:gallary' %}">Gallary</a>
            <a href="{% url 'my_app:players' %}">Players</a>
            <a href="{% url 'my_app:about' %}">About Us</a>
            <a href="{% url 'my_app:contact' %}">Contact Us</a>



        </div>
    </div>
    <br><br><br><br><br><br>

    <div class="heading1">
        <h1>Latest Images</h1>
    </div>
    <br><br><br>

    <div class="grid-wrapper">

        <div class="gall">
            <img src="{% static 'images/gallary1.webp' %}" alt="">
        </div>

        <div class="gall">
            <img src="{% static 'images/gallary16.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary25.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary4.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary5.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary6.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary7.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary8.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary9.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary10.png' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary11.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary12.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary13.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary14.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary15.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary16.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary17.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary18.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary19.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary20.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary21.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary22.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary23.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary24.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary25.jpg' %}" alt="">
        </div>

        <div class="gall">
            <img src="{% static 'images/gallary27.webp' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary28.jpg' %}" alt="">
        </div>
        <div class="gall">
            <img src="{% static 'images/gallary29.jpg' %}" alt="">
        </div>

    </div>
    <br><br><br>

    <div class="container4">
        <div><img src="{% static 'images/byjus.png' %}" alt=""></div>
        <div><img src="{% static 'images/star.png' %}" alt=""></div>
        <div><img src="{% static 'images/mpl.png' %}" alt=""></div>
        <div><img src="{% static 'images/hyundai.png' %}" alt=""></div>
        <div><img src="{% static 'images/dream11.png' %}" alt=""></div>
        <div><img src="{% static 'images/ambuja.png' %}" alt=""></div>
        <div><img src="{% static 'images/master-card.png' %}" alt=""></div>


    </div>
    <br><br><br><br>
    <div class="footer">
        <div>
            <h1>T +91 22 - 2289 8800

                F 022 - 2289 8801</h1>
        </div>
        <div>
            <h1>Copyrights BCCI 2021 , All Rights Reserved.</h1>
        </div>
        <div>
            <h1>Terms and Conditions</h1>
        </div>
        <div>
            <h1>Privacy Policy</h1>
        </div>

    </div>


</body>

</html>

my_app/templates/my_app_templates/players.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_player.css' %}">
    <title>Players page</title>
</head>

<body>
    <div class="container1">

        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>
        <div class="navRight">

            <a href="{% url 'my_app:home' %}">Home</a>
            <a href="{% url 'my_app:gallary' %}">Gallary</a>
            <a href="{% url 'my_app:players' %}">Players</a>
            <a href="{% url 'my_app:about' %}">About Us</a>
            <a href="{% url 'my_app:contact' %}">Contact Us</a>

        </div>
    </div>
    <br><br><br><br><br><br><br><br>

    <div class="grade">
        <h1>GRADE A+</h1>
    </div>

    <div class="container2">
        <div class="card">
            <img src="{% static 'images/player1.png' %}" alt="">
            <div class="info">
                <h1>VIRAT
                    <br>
                    <h2>Kohli</h2>
                </h1>
                <p>
                <h1>Batter</h1>
                </p>
                <a href="#" class="btn">Read More</a>
            </div>


        </div>

        <div class="card">
            <img src="{% static 'images/player2.png' %}" alt="">
            <div class="info">
                <h1>ROHIT <br>
                    <h2>Sharma</h2>
                </h1>

                <p>Batter</p>
                <a href="#" class="btn">Read More</a>
            </div>


        </div>

        <div class="card">
            <img src="{% static 'images/player3.png' %}" alt="">
            <div class="info">
                <h1>JASPRIT <br>
                    <h2>Bumrah</h2>
                </h1>

                <p>Bowler</p>
                <a href="#" class="btn">Read More</a>
            </div>
        </div>



    </div>

    <br><br><br><br><br>

    <div class="grade">
        <h1>GRADE B</h1>
    </div>

    <div class="container2">
        <div class="card">
            <img src="{% static 'images/grade2.png' %}" alt="">
            <div class="info">
                <h1>RAVINDRA
                    <br>
                    <h2>Jadeja</h2>
                </h1>
                <p>
                <h1>All- rounder</h1>
                </p>
                <a href="#" class="btn">Read More</a>
            </div>


        </div>

        <div class="card">
            <img src="{% static 'images/grade2 b.png' %}" alt="">
            <div class="info">
                <h1>CHETESHWAR <br>
                    <h2>Pujara</h2>
                </h1>

                <p>Batter</p>
                <a href="#" class="btn">Read More</a>
            </div>


        </div>

        <div class="card">
            <img src="{% static 'images/grade2 c.png' %}" alt="">
            <div class="info">
                <h1>JASPRIT <br>
                    <h2>Bumrah</h2>
                </h1>

                <p>Bowler</p>
                <a href="#" class="btn">Read More</a>
            </div>
        </div>

        <div class="card">
            <img src="{% static 'images/grade2 d.png' %}" alt="">
            <div class="info">
                <h1>AJINKYA <br>
                    <h2>Rahane</h2>
                </h1>

                <p>Bowler</p>
                <a href="#" class="btn">Read More</a>
            </div>
        </div>



    </div>

    <!--  -->

    <br><br><br><br><br>

    <div class="grade">
        <h1>GRADE C</h1>
    </div>

    <div class="container2">
        <div class="card">
            <img src="{% static 'images/grade3 a.png' %}" alt="">
            <div class="info">
                <h1>RAVINDRA
                    <br>
                    <h2>Jadeja</h2>
                </h1>
                <p>
                <h1>All- rounder</h1>
                </p>
                <a href="#" class="btn">Read More</a>
            </div>


        </div>

        <div class="card">
            <img src="{% static 'images/grade3 b.png' %}" alt="">
            <div class="info">
                <h1>CHETESHWAR <br>
                    <h2>Pujara</h2>
                </h1>

                <p>Batter</p>
                <a href="#" class="btn">Read More</a>
            </div>


        </div>

        <div class="card">
            <img src="{% static 'images/grade3 3.png' %}" alt="">
            <div class="info">
                <h1>JASPRIT <br>
                    <h2>Bumrah</h2>
                </h1>

                <p>Bowler</p>
                <a href="#" class="btn">Read More</a>
            </div>
        </div>

        <div class="card">
            <img src="{% static 'images/grade3 4.png' %}" alt="">
            <div class="info">
                <h1>AJINKYA <br>
                    <h2>Rahane</h2>
                </h1>

                <p>Bowler</p>
                <a href="#" class="btn">Read More</a>
            </div>
        </div>
    </div>

    <br><br><br><br>

    <!-- FOOTER -->
    <div class="footer">
        <div>
            <h1>T +91 22 - 2289 8800

                F 022 - 2289 8801</h1>
        </div>
        <div>
            <h1>Copyrights BCCI 2021 , All Rights Reserved.</h1>
        </div>
        <div>
            <h1>Terms and Conditions</h1>
        </div>
        <div>
            <h1>Privacy Policy</h1>
        </div>

    </div>

</body>